import type { IconType } from 'react-icons'
import {
  SiSamsung,
  SiLg,
  SiXiaomi,
  SiApple,
  SiGooglehome,
  SiPhilipshue,
  SiSonos,
  SiIkea,
  SiRing,
  SiArlo,
  SiSmartthings,
  SiHomeassistant,
  SiTplink,
  SiEcovacs,
  SiBosch,
  SiSiemens,
  SiNetgear,
  SiTado,
  SiWemo,
  SiSchneiderelectric,
  SiPanasonic,
  SiWyze,
  SiHuawei,
  SiLenovo,
  SiAsus,
  SiAcer,
  SiYale,
  SiBose,
  SiSony,
  SiHive,
} from 'react-icons/si'

export interface Brand {
  name: string
  Icon: IconType
}

export const trustedBrands: Brand[] = [
  { name: 'Samsung', Icon: SiSamsung },
  { name: 'LG', Icon: SiLg },
  { name: 'Xiaomi', Icon: SiXiaomi },
  { name: 'Apple HomeKit', Icon: SiApple },
  { name: 'Google Home', Icon: SiGooglehome },
  { name: 'Philips Hue', Icon: SiPhilipshue },
  { name: 'Sonos', Icon: SiSonos },
  { name: 'IKEA Home Smart', Icon: SiIkea },
  { name: 'Ring', Icon: SiRing },
  { name: 'Arlo', Icon: SiArlo },
  { name: 'SmartThings', Icon: SiSmartthings },
  { name: 'Home Assistant', Icon: SiHomeassistant },
  { name: 'TP-Link', Icon: SiTplink },
  { name: 'Ecovacs', Icon: SiEcovacs },
  { name: 'Bosch', Icon: SiBosch },
  { name: 'Siemens', Icon: SiSiemens },
  { name: 'Netgear', Icon: SiNetgear },
  { name: 'Tado°', Icon: SiTado },
  { name: 'Wemo', Icon: SiWemo },
  { name: 'Schneider Electric', Icon: SiSchneiderelectric },
  { name: 'Panasonic', Icon: SiPanasonic },
  { name: 'Wyze', Icon: SiWyze },
  { name: 'Huawei', Icon: SiHuawei },
  { name: 'Lenovo', Icon: SiLenovo },
  { name: 'ASUS', Icon: SiAsus },
  { name: 'Acer', Icon: SiAcer },
  { name: 'Yale', Icon: SiYale },
  { name: 'Bose', Icon: SiBose },
  { name: 'Sony', Icon: SiSony },
  { name: 'Hive', Icon: SiHive },
]

